const mongoose = require('mongoose');
require('dotenv').config();

// Sample products data with correct images and business types
const sampleProducts = [
  {
    name: "Premium Basmati Rice",
    description: "Long grain premium quality basmati rice, perfect for all Indian dishes",
    category: "Food & Beverages",
    subcategory: "Rice & Grains", 
    brand: "India Gate",
    sku: "IG-BASMATI-5KG",
    price: { mrp: 110, discountedPrice: 100, discount: 9.09 },
    inventory: { stock: 150, minStock: 20, maxStock: 500, unit: "kg" },
    specifications: { weight: "5kg", expiryDate: new Date(Date.now() + 365*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1586201375761-83865001e8c3?w=400&h=400&fit=crop&crop=center"],
    tags: ["organic", "premium", "basmati"],
    features: ["Long grain", "Aromatic", "Premium quality"],
    ratings: { average: 4.5, count: 120 },
    analytics: { views: 450, purchases: 89, trendingScore: 85 },
    supplier: { name: "Rice Distributors Ltd", contact: "+91 9876543210" },
    isFeatured: true,
    isNewLaunch: false,
    businessType: "grocery"
  },
  {
    name: "Almonds 500g",
    description: "Premium California almonds, rich in protein and healthy fats",
    category: "Groceries",
    subcategory: "Dry Fruits & Nuts",
    brand: "NuttyDelight",
    sku: "ND-ALMONDS-500G",
    price: { mrp: 110, discountedPrice: 105, discount: 4.55 },
    inventory: { stock: 85, minStock: 10, maxStock: 200, unit: "pieces" },
    specifications: { weight: "500g", expiryDate: new Date(Date.now() + 365*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1508747703725-719777637510?w=400&h=400&fit=crop&crop=center"],
    tags: ["premium", "california", "protein", "healthy"],
    features: ["High protein", "Rich in healthy fats", "Premium quality"],
    ratings: { average: 4.3, count: 110 },
    analytics: { views: 320, purchases: 68, trendingScore: 75 },
    supplier: { name: "Dry Fruit Traders", contact: "+91 9876543215" },
    isFeatured: false,
    isNewLaunch: false,
    businessType: "grocery"
  },
  {
    name: "Basmati Rice 5kg",
    description: "Premium long grain basmati rice, aromatic and fluffy",
    category: "Groceries", 
    subcategory: "Rice & Grains",
    brand: "GoldenGrain",
    sku: "GG-BASMATI-5KG",
    price: { mrp: 108, discountedPrice: 100, discount: 7.41 },
    inventory: { stock: 164, minStock: 20, maxStock: 500, unit: "pieces" },
    specifications: { weight: "5kg", expiryDate: new Date(Date.now() + 730*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1586201375761-83865001e8c3?w=400&h=400&fit=crop&crop=center"],
    tags: ["premium", "long grain", "aromatic", "basmati"],
    features: ["Long grain", "Aromatic", "Fluffy texture"],
    ratings: { average: 4.2, count: 114 },
    analytics: { views: 450, purchases: 89, trendingScore: 85 },
    supplier: { name: "Rice Distributors Ltd", contact: "+91 9876543216" },
    isFeatured: true,
    isNewLaunch: false,
    businessType: "grocery"
  },
  {
    name: "Brown Bread Loaf",
    description: "Fresh whole wheat brown bread, rich in fiber and nutrients",
    category: "Groceries",
    subcategory: "Bakery",
    brand: "BreadBasket", 
    sku: "BB-BROWN-LOAF",
    price: { mrp: 50, discountedPrice: 45, discount: 10 },
    inventory: { stock: 177, minStock: 30, maxStock: 300, unit: "pieces" },
    specifications: { weight: "400g", expiryDate: new Date(Date.now() + 3*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop&crop=center"],
    tags: ["whole wheat", "fiber", "fresh", "healthy"],
    features: ["Rich in fiber", "Whole wheat", "Fresh daily"],
    ratings: { average: 3.9, count: 78 },
    analytics: { views: 290, purchases: 55, trendingScore: 62 },
    supplier: { name: "Fresh Bakery Co", contact: "+91 9876543217" },
    isFeatured: false,
    isNewLaunch: true,
    businessType: "grocery"
  },
  {
    name: "Fresh Milk 1L",
    description: "Fresh full cream milk, rich in calcium and proteins",
    category: "Groceries",
    subcategory: "Dairy",
    brand: "DairyFresh",
    sku: "DF-MILK-1L",
    price: { mrp: 55, discountedPrice: 50, discount: 9.09 },
    inventory: { stock: 230, minStock: 50, maxStock: 400, unit: "pieces" },
    specifications: { volume: "1L", expiryDate: new Date(Date.now() + 2*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=400&fit=crop&crop=center"],
    tags: ["fresh", "full cream", "calcium", "protein"],
    features: ["Full cream", "Rich in calcium", "Fresh daily"],
    ratings: { average: 4.4, count: 150 },
    analytics: { views: 380, purchases: 95, trendingScore: 88 },
    supplier: { name: "Dairy Products Ltd", contact: "+91 9876543218" },
    isFeatured: true,
    isNewLaunch: false,
    businessType: "grocery"
  },
  {
    name: "Organic Whole Wheat Flour",
    description: "100% organic whole wheat flour, stone ground for better nutrition",
    category: "Food & Beverages",
    subcategory: "Flour & Grains",
    brand: "Aashirvaad",
    sku: "ASH-WHEAT-10KG",
    price: { mrp: 110, discountedPrice: 105, discount: 4.55 },
    inventory: { stock: 200, minStock: 30, maxStock: 800, unit: "kg" },
    specifications: { weight: "10kg", expiryDate: new Date(Date.now() + 180*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=400&fit=crop&crop=center"],
    tags: ["organic", "healthy", "stone-ground"],
    features: ["100% organic", "Stone ground", "High fiber"],
    ratings: { average: 4.3, count: 95 },
    analytics: { views: 320, purchases: 67, trendingScore: 78 },
    supplier: { name: "Grain Suppliers Co", contact: "+91 9876543211" },
    isFeatured: false,
    isNewLaunch: true,
    businessType: "grocery"
  },
  {
    name: "Kurkure Masala Munch 90g",
    description: "Crunchy corn puffs with tangy masala flavor",
    category: "Snacks",
    subcategory: "Chips & Namkeen",
    brand: "Kurkure",
    sku: "KUR-MASALA-90G",
    price: { mrp: 25, discountedPrice: 22, discount: 12 },
    inventory: { stock: 400, minStock: 80, maxStock: 1000, unit: "pieces" },
    specifications: { weight: "90g", expiryDate: new Date(Date.now() + 180*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1613919113640-25732ec5e61f?w=400&h=400&fit=crop&crop=center"],
    tags: ["snacks", "crunchy", "masala", "corn puffs"],
    features: ["Crunchy texture", "Tangy flavor", "Popular snack"],
    ratings: { average: 4.2, count: 250 },
    analytics: { views: 650, purchases: 185, trendingScore: 92 },
    supplier: { name: "Snack Foods Ltd", contact: "+91 9876543241" },
    isFeatured: true,
    isNewLaunch: false,
    businessType: "grocery"
  },
  {
    name: "Horlicks Health Drink 500g",
    description: "Nutritious malt-based health drink for all ages",
    category: "Beverages",
    subcategory: "Health Drinks",
    brand: "Horlicks",
    sku: "HOR-HEALTH-500G",
    price: { mrp: 105, discountedPrice: 95, discount: 9.52 },
    inventory: { stock: 120, minStock: 25, maxStock: 400, unit: "pieces" },
    specifications: { weight: "500g", expiryDate: new Date(Date.now() + 365*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&h=400&fit=crop&crop=center"],
    tags: ["health drink", "malt", "nutrition", "energy"],
    features: ["Rich in vitamins", "Energy booster", "Family pack"],
    ratings: { average: 4.5, count: 180 },
    analytics: { views: 480, purchases: 125, trendingScore: 88 },
    supplier: { name: "Health Beverages Co", contact: "+91 9876543242" },
    isFeatured: true,
    isNewLaunch: false,
    businessType: "grocery"
  },
  {
    name: "Maggi Noodles 70g",
    description: "Instant noodles with masala flavor - 2 minute cooking",
    category: "Instant Food",
    subcategory: "Noodles",
    brand: "Maggi",
    sku: "MAG-NOODLES-70G",
    price: { mrp: 14, discountedPrice: 12, discount: 14.29 },
    inventory: { stock: 500, minStock: 100, maxStock: 1200, unit: "pieces" },
    specifications: { weight: "70g", expiryDate: new Date(Date.now() + 365*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=400&fit=crop&crop=center"],
    tags: ["instant noodles", "quick meal", "masala", "convenient"],
    features: ["2 minute cooking", "Masala flavor", "Quick meal"],
    ratings: { average: 4.3, count: 320 },
    analytics: { views: 720, purchases: 220, trendingScore: 95 },
    supplier: { name: "Instant Foods Ltd", contact: "+91 9876543243" },
    isFeatured: false,
    isNewLaunch: false,
    businessType: "grocery"
  },
  {
    name: "Parle-G Biscuits 100g",
    description: "Classic glucose biscuits perfect with tea",
    category: "Bakery",
    subcategory: "Biscuits",
    brand: "Parle",
    sku: "PAR-GLUCOSE-100G",
    price: { mrp: 12, discountedPrice: 10, discount: 16.67 },
    inventory: { stock: 600, minStock: 120, maxStock: 1500, unit: "pieces" },
    specifications: { weight: "100g", expiryDate: new Date(Date.now() + 120*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&h=400&fit=crop&crop=center"],
    tags: ["biscuits", "glucose", "tea time", "classic"],
    features: ["Glucose enriched", "Tea companion", "Iconic taste"],
    ratings: { average: 4.4, count: 280 },
    analytics: { views: 580, purchases: 195, trendingScore: 90 },
    supplier: { name: "Biscuit Manufacturers", contact: "+91 9876543244" },
    isFeatured: false,
    isNewLaunch: false,
    businessType: "grocery"
  },
  {
    name: "Tata Tea Premium 250g",
    description: "Premium black tea blend for perfect morning brew",
    category: "Beverages",
    subcategory: "Tea",
    brand: "Tata Tea",
    sku: "TATA-TEA-250G",
    price: { mrp: 85, discountedPrice: 78, discount: 8.24 },
    inventory: { stock: 180, minStock: 35, maxStock: 600, unit: "pieces" },
    specifications: { weight: "250g", expiryDate: new Date(Date.now() + 730*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1594631661960-28ea2e4b8faa?w=400&h=400&fit=crop&crop=center"],
    tags: ["tea", "black tea", "premium", "morning"],
    features: ["Premium blend", "Rich flavor", "Perfect strength"],
    ratings: { average: 4.3, count: 165 },
    analytics: { views: 420, purchases: 115, trendingScore: 82 },
    supplier: { name: "Tea Traders Co", contact: "+91 9876543245" },
    isFeatured: false,
    isNewLaunch: false,
    businessType: "grocery"
  },
  {
    name: "Cadbury Dairy Milk 55g",
    description: "Creamy milk chocolate bar - classic taste",
    category: "Confectionery",
    subcategory: "Chocolates",
    brand: "Cadbury",
    sku: "CAD-DAIRYMILK-55G",
    price: { mrp: 35, discountedPrice: 32, discount: 8.57 },
    inventory: { stock: 320, minStock: 60, maxStock: 800, unit: "pieces" },
    specifications: { weight: "55g", expiryDate: new Date(Date.now() + 365*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=400&h=400&fit=crop&crop=center"],
    tags: ["chocolate", "milk chocolate", "sweet", "treat"],
    features: ["Creamy texture", "Rich cocoa", "Classic taste"],
    ratings: { average: 4.6, count: 295 },
    analytics: { views: 680, purchases: 205, trendingScore: 94 },
    supplier: { name: "Chocolate Distributors", contact: "+91 9876543246" },
    isFeatured: true,
    isNewLaunch: false,
    businessType: "grocery"
  },
  {
    name: "Surf Excel Detergent 1kg",
    description: "Powerful stain removal detergent powder",
    category: "Household",
    subcategory: "Cleaning",
    brand: "Surf Excel",
    sku: "SUR-DETERGENT-1KG",
    price: { mrp: 95, discountedPrice: 88, discount: 7.37 },
    inventory: { stock: 140, minStock: 25, maxStock: 450, unit: "pieces" },
    specifications: { weight: "1kg", expiryDate: new Date(Date.now() + 1095*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&h=400&fit=crop&crop=center"],
    tags: ["detergent", "cleaning", "stain removal", "washing"],
    features: ["Tough on stains", "Gentle on fabric", "Long lasting"],
    ratings: { average: 4.2, count: 155 },
    analytics: { views: 380, purchases: 95, trendingScore: 78 },
    supplier: { name: "Home Care Products", contact: "+91 9876543247" },
    isFeatured: false,
    isNewLaunch: false,
    businessType: "grocery"
  },
  {
    name: "Lays Classic Salted 52g",
    description: "Crispy potato chips with perfect salt seasoning",
    category: "Snacks",
    subcategory: "Chips & Namkeen",
    brand: "Lays",
    sku: "LAY-SALTED-52G",
    price: { mrp: 20, discountedPrice: 18, discount: 10 },
    inventory: { stock: 450, minStock: 90, maxStock: 1000, unit: "pieces" },
    specifications: { weight: "52g", expiryDate: new Date(Date.now() + 120*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&h=400&fit=crop&crop=center"],
    tags: ["chips", "potato", "salted", "crispy"],
    features: ["Crispy texture", "Perfect salt", "Fresh potatoes"],
    ratings: { average: 4.1, count: 210 },
    analytics: { views: 520, purchases: 165, trendingScore: 88 },
    supplier: { name: "Snack Foods Ltd", contact: "+91 9876543248" },
    isFeatured: false,
    isNewLaunch: false,
    businessType: "grocery"
  },
  {
    name: "Colgate Toothpaste 100g",
    description: "Advanced cavity protection toothpaste",
    category: "Personal Care",
    subcategory: "Oral Care",
    brand: "Colgate",
    sku: "COL-TOOTHPASTE-100G",
    price: { mrp: 65, discountedPrice: 58, discount: 10.77 },
    inventory: { stock: 250, minStock: 50, maxStock: 700, unit: "pieces" },
    specifications: { weight: "100g", expiryDate: new Date(Date.now() + 730*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&crop=center"],
    tags: ["toothpaste", "oral care", "cavity protection", "dental"],
    features: ["Cavity protection", "Fresh breath", "Fluoride formula"],
    ratings: { average: 4.4, count: 190 },
    analytics: { views: 450, purchases: 135, trendingScore: 85 },
    supplier: { name: "Personal Care Co", contact: "+91 9876543249" },
    isFeatured: false,
    isNewLaunch: false,
    businessType: "grocery"
  },
  {
    name: "Amul Butter 100g",
    description: "Fresh salted butter made from pure cream",
    category: "Dairy",
    subcategory: "Butter & Spreads",
    brand: "Amul",
    sku: "AMU-BUTTER-100G",
    price: { mrp: 58, discountedPrice: 52, discount: 10.34 },
    inventory: { stock: 160, minStock: 30, maxStock: 500, unit: "pieces" },
    specifications: { weight: "100g", expiryDate: new Date(Date.now() + 60*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400&h=400&fit=crop&crop=center"],
    tags: ["butter", "dairy", "spread", "fresh"],
    features: ["Pure cream", "Salted butter", "Fresh quality"],
    ratings: { average: 4.5, count: 170 },
    analytics: { views: 390, purchases: 110, trendingScore: 80 },
    supplier: { name: "Dairy Cooperative", contact: "+91 9876543250" },
    isFeatured: false,
    isNewLaunch: false,
    businessType: "grocery"
  },
  {
    name: "Fresh Dairy Milk 1L",
    description: "Fresh whole milk, rich in calcium and protein, perfect for daily consumption",
    category: "Dairy",
    subcategory: "Milk & Cream",
    brand: "Mother Dairy",
    sku: "MD-MILK-1L",
    price: { mrp: 65, discountedPrice: 60, discount: 7.69 },
    inventory: { stock: 200, minStock: 50, maxStock: 800, unit: "pieces" },
    specifications: { weight: "1L", expiryDate: new Date(Date.now() + 3*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=400&fit=crop&crop=center"],
    tags: ["milk", "dairy", "fresh", "calcium", "protein"],
    features: ["Rich in calcium", "High protein", "Fresh daily", "Pasteurized"],
    ratings: { average: 4.6, count: 220 },
    analytics: { views: 520, purchases: 180, trendingScore: 90 },
    supplier: { name: "Dairy Cooperative", contact: "+91 9876543250" },
    isFeatured: true,
    isNewLaunch: false,
    businessType: "grocery"
  },
  // Add pharmacy products
  {
    name: "Paracetamol Tablets 500mg",
    description: "Pain relief and fever reducer tablets - 20 tablets pack",
    category: "Medicine",
    subcategory: "Pain Relief",
    brand: "Crocin",
    sku: "CRC-PARA-500MG",
    price: { mrp: 35, discountedPrice: 30, discount: 14.29 },
    inventory: { stock: 500, minStock: 100, maxStock: 1000, unit: "pieces" },
    specifications: { weight: "500mg", expiryDate: new Date(Date.now() + 730*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop&crop=center"],
    tags: ["pain relief", "fever", "tablets", "medicine"],
    features: ["Fast acting", "Fever reducer", "Safe for adults"],
    ratings: { average: 4.5, count: 200 },
    analytics: { views: 600, purchases: 150, trendingScore: 90 },
    supplier: { name: "Pharma Distributors", contact: "+91 9876543220" },
    isFeatured: true,
    isNewLaunch: false,
    businessType: "pharmacy"
  },
  {
    name: "Hand Sanitizer 100ml",
    description: "70% alcohol based hand sanitizer for effective germ protection",
    category: "Personal Care",
    subcategory: "Hygiene",
    brand: "Dettol",
    sku: "DET-SANITIZER-100ML",
    price: { mrp: 65, discountedPrice: 60, discount: 7.69 },
    inventory: { stock: 300, minStock: 50, maxStock: 800, unit: "pieces" },
    specifications: { volume: "100ml", expiryDate: new Date(Date.now() + 1095*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1584744982491-665216d95f8b?w=400&h=400&fit=crop&crop=center"],
    tags: ["sanitizer", "hygiene", "alcohol", "germs"],
    features: ["70% alcohol", "Kills 99.9% germs", "Pocket friendly"],
    ratings: { average: 4.2, count: 180 },
    analytics: { views: 450, purchases: 120, trendingScore: 85 },
    supplier: { name: "Healthcare Suppliers", contact: "+91 9876543221" },
    isFeatured: false,
    isNewLaunch: false,
    businessType: "pharmacy"
  },
  {
    name: "Vitamin C Tablets",
    description: "Immune system support with 1000mg Vitamin C - 30 tablets",
    category: "Medicine",
    subcategory: "Vitamins & Supplements",
    brand: "HealthPlus",
    sku: "HP-VITC-1000MG",
    price: { mrp: 85, discountedPrice: 75, discount: 11.76 },
    inventory: { stock: 200, minStock: 40, maxStock: 600, unit: "pieces" },
    specifications: { weight: "1000mg", expiryDate: new Date(Date.now() + 730*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop&crop=center"],
    tags: ["vitamin", "immune", "health", "supplement"],
    features: ["Immune support", "High potency", "Easy to swallow"],
    ratings: { average: 4.3, count: 95 },
    analytics: { views: 280, purchases: 65, trendingScore: 70 },
    supplier: { name: "Health Supplements Co", contact: "+91 9876543224" },
    isFeatured: false,
    isNewLaunch: false,
    businessType: "pharmacy"
  },
  {
    name: "Antiseptic Cream 50g",
    description: "Multi-purpose antiseptic cream for cuts and wounds",
    category: "Medicine",
    subcategory: "First Aid",
    brand: "Savlon",
    sku: "SAV-ANTISEPTIC-50G",
    price: { mrp: 90, discountedPrice: 80, discount: 11.11 },
    inventory: { stock: 150, minStock: 30, maxStock: 400, unit: "pieces" },
    specifications: { weight: "50g", expiryDate: new Date(Date.now() + 1095*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400&h=400&fit=crop&crop=center"],
    tags: ["antiseptic", "healing", "first aid", "wounds"],
    features: ["Fast healing", "Prevents infection", "Gentle on skin"],
    ratings: { average: 4.4, count: 130 },
    analytics: { views: 350, purchases: 85, trendingScore: 75 },
    supplier: { name: "Medical Supplies Ltd", contact: "+91 9876543225" },
    isFeatured: true,
    isNewLaunch: false,
    businessType: "pharmacy"
  },
  {
    name: "Cough Syrup 100ml",
    description: "Effective relief from dry and wet cough - honey based",
    category: "Medicine",
    subcategory: "Cough & Cold",
    brand: "Benadryl",
    sku: "BEN-COUGH-100ML",
    price: { mrp: 95, discountedPrice: 85, discount: 10.53 },
    inventory: { stock: 120, minStock: 25, maxStock: 350, unit: "pieces" },
    specifications: { volume: "100ml", expiryDate: new Date(Date.now() + 730*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop&crop=center"],
    tags: ["cough", "syrup", "relief", "honey"],
    features: ["Natural honey", "Fast relief", "Pleasant taste"],
    ratings: { average: 4.1, count: 88 },
    analytics: { views: 300, purchases: 70, trendingScore: 68 },
    supplier: { name: "Pharma Distributors", contact: "+91 9876543226" },
    isFeatured: false,
    isNewLaunch: false,
    businessType: "pharmacy"
  },
  {
    name: "Digital Thermometer",
    description: "Fast and accurate digital fever thermometer",
    category: "Medical Devices",
    subcategory: "Monitoring",
    brand: "Omron",
    sku: "OMR-THERMO-DIG",
    price: { mrp: 110, discountedPrice: 100, discount: 9.09 },
    inventory: { stock: 75, minStock: 15, maxStock: 200, unit: "pieces" },
    specifications: { weight: "50g", expiryDate: new Date(Date.now() + 1825*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400&h=400&fit=crop&crop=center"],
    tags: ["thermometer", "digital", "fever", "medical"],
    features: ["Fast reading", "Accurate", "Easy to use"],
    ratings: { average: 4.6, count: 145 },
    analytics: { views: 420, purchases: 110, trendingScore: 82 },
    supplier: { name: "Medical Equipment Co", contact: "+91 9876543227" },
    isFeatured: true,
    isNewLaunch: false,
    businessType: "pharmacy"
  },
  {
    name: "Bandage Roll 5m",
    description: "Sterile cotton bandage for wound dressing - 5 meter roll",
    category: "Medical Supplies",
    subcategory: "Wound Care",
    brand: "Johnson & Johnson",
    sku: "JJ-BANDAGE-5M",
    price: { mrp: 70, discountedPrice: 65, discount: 7.14 },
    inventory: { stock: 180, minStock: 35, maxStock: 500, unit: "pieces" },
    specifications: { length: "5m", expiryDate: new Date(Date.now() + 1460*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=400&h=400&fit=crop&crop=center"],
    tags: ["bandage", "sterile", "wound care", "cotton"],
    features: ["Sterile", "Breathable", "Easy to apply"],
    ratings: { average: 4.2, count: 75 },
    analytics: { views: 250, purchases: 55, trendingScore: 60 },
    supplier: { name: "Medical Supplies Ltd", contact: "+91 9876543228" },
    isFeatured: false,
    isNewLaunch: false,
    businessType: "pharmacy"
  },
  {
    name: "Blood Pressure Monitor",
    description: "Digital automatic blood pressure monitor with large display",
    category: "Medical Devices",
    subcategory: "Monitoring",
    brand: "Omron",
    sku: "OMR-BP-MONITOR",
    price: { mrp: 110, discountedPrice: 105, discount: 4.55 },
    inventory: { stock: 45, minStock: 10, maxStock: 150, unit: "pieces" },
    specifications: { weight: "300g", expiryDate: new Date(Date.now() + 1825*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop&crop=center"],
    tags: ["blood pressure", "monitor", "digital", "healthcare"],
    features: ["Automatic inflation", "Large display", "Memory storage"],
    ratings: { average: 4.7, count: 165 },
    analytics: { views: 480, purchases: 125, trendingScore: 88 },
    supplier: { name: "Medical Equipment Co", contact: "+91 9876543229" },
    isFeatured: true,
    isNewLaunch: false,
    businessType: "pharmacy"
  },
  {
    name: "Multivitamin Tablets",
    description: "Complete multivitamin with minerals - 60 tablets",
    category: "Medicine",
    subcategory: "Vitamins & Supplements",
    brand: "Centrum",
    sku: "CEN-MULTI-60T",
    price: { mrp: 95, discountedPrice: 88, discount: 7.37 },
    inventory: { stock: 220, minStock: 45, maxStock: 700, unit: "pieces" },
    specifications: { weight: "100g", expiryDate: new Date(Date.now() + 730*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop&crop=center"],
    tags: ["multivitamin", "minerals", "health", "daily"],
    features: ["Complete nutrition", "Daily formula", "Easy to swallow"],
    ratings: { average: 4.4, count: 190 },
    analytics: { views: 380, purchases: 95, trendingScore: 78 },
    supplier: { name: "Health Supplements Co", contact: "+91 9876543230" },
    isFeatured: false,
    isNewLaunch: false,
    businessType: "pharmacy"
  },
  {
    name: "Antacid Tablets",
    description: "Fast relief from acidity and heartburn - 20 tablets",
    category: "Medicine",
    subcategory: "Digestive Health",
    brand: "ENO",
    sku: "ENO-ANTACID-20T",
    price: { mrp: 45, discountedPrice: 40, discount: 11.11 },
    inventory: { stock: 350, minStock: 70, maxStock: 800, unit: "pieces" },
    specifications: { weight: "40g", expiryDate: new Date(Date.now() + 730*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop&crop=center"],
    tags: ["antacid", "acidity", "heartburn", "digestive"],
    features: ["Fast acting", "Gentle formula", "Chewable"],
    ratings: { average: 4.2, count: 145 },
    analytics: { views: 320, purchases: 78, trendingScore: 72 },
    supplier: { name: "Pharma Distributors", contact: "+91 9876543231" },
    isFeatured: false,
    isNewLaunch: false,
    businessType: "pharmacy"
  },
  {
    name: "Eye Drops 10ml",
    description: "Lubricating eye drops for dry eyes and irritation",
    category: "Medicine",
    subcategory: "Eye Care",
    brand: "Refresh",
    sku: "REF-EYEDROPS-10ML",
    price: { mrp: 75, discountedPrice: 68, discount: 9.33 },
    inventory: { stock: 160, minStock: 30, maxStock: 450, unit: "pieces" },
    specifications: { volume: "10ml", expiryDate: new Date(Date.now() + 730*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400&h=400&fit=crop&crop=center"],
    tags: ["eye drops", "dry eyes", "lubricating", "vision"],
    features: ["Preservative free", "Long lasting", "Gentle formula"],
    ratings: { average: 4.3, count: 110 },
    analytics: { views: 290, purchases: 65, trendingScore: 68 },
    supplier: { name: "Eye Care Specialists", contact: "+91 9876543232" },
    isFeatured: false,
    isNewLaunch: false,
    businessType: "pharmacy"
  },
  {
    name: "Pain Relief Gel 30g",
    description: "Topical pain relief gel for muscle and joint pain",
    category: "Medicine",
    subcategory: "Pain Relief",
    brand: "Volini",
    sku: "VOL-PAINGEL-30G",
    price: { mrp: 85, discountedPrice: 78, discount: 8.24 },
    inventory: { stock: 140, minStock: 25, maxStock: 400, unit: "pieces" },
    specifications: { weight: "30g", expiryDate: new Date(Date.now() + 1095*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=400&h=400&fit=crop&crop=center"],
    tags: ["pain relief", "gel", "muscle", "joint"],
    features: ["Fast absorption", "Non-greasy", "Cooling effect"],
    ratings: { average: 4.1, count: 125 },
    analytics: { views: 340, purchases: 82, trendingScore: 75 },
    supplier: { name: "Pain Care Solutions", contact: "+91 9876543233" },
    isFeatured: false,
    isNewLaunch: false,
    businessType: "pharmacy"
  },
  {
    name: "Glucose Meter Kit",
    description: "Blood glucose monitoring system with test strips",
    category: "Medical Devices",
    subcategory: "Diabetes Care",
    brand: "Accu-Chek",
    sku: "ACC-GLUCOSE-KIT",
    price: { mrp: 110, discountedPrice: 100, discount: 9.09 },
    inventory: { stock: 35, minStock: 8, maxStock: 120, unit: "pieces" },
    specifications: { weight: "150g", expiryDate: new Date(Date.now() + 1825*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400&h=400&fit=crop&crop=center"],
    tags: ["glucose", "diabetes", "monitor", "blood sugar"],
    features: ["Quick results", "Easy to use", "Accurate readings"],
    ratings: { average: 4.6, count: 88 },
    analytics: { views: 280, purchases: 55, trendingScore: 70 },
    supplier: { name: "Diabetes Care Co", contact: "+91 9876543234" },
    isFeatured: true,
    isNewLaunch: false,
    businessType: "pharmacy"
  },
  {
    name: "Surgical Face Masks",
    description: "3-layer disposable surgical face masks - Pack of 50",
    category: "Medical Supplies",
    subcategory: "Personal Protection",
    brand: "MedSafe",
    sku: "MED-MASK-50PK",
    price: { mrp: 90, discountedPrice: 82, discount: 8.89 },
    inventory: { stock: 200, minStock: 40, maxStock: 600, unit: "pieces" },
    specifications: { weight: "250g", expiryDate: new Date(Date.now() + 1095*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1584744982491-665216d95f8b?w=400&h=400&fit=crop&crop=center"],
    tags: ["face masks", "surgical", "disposable", "protection"],
    features: ["3-layer protection", "Comfortable fit", "Breathable"],
    ratings: { average: 4.3, count: 220 },
    analytics: { views: 520, purchases: 140, trendingScore: 85 },
    supplier: { name: "Safety Equipment Ltd", contact: "+91 9876543235" },
    isFeatured: false,
    isNewLaunch: false,
    businessType: "pharmacy"
  },
  {
    name: "Cold & Flu Tablets",
    description: "Multi-symptom cold and flu relief tablets - 12 tablets",
    category: "Medicine",
    subcategory: "Cough & Cold",
    brand: "Sinarest",
    sku: "SIN-COLDFLU-12T",
    price: { mrp: 55, discountedPrice: 48, discount: 12.73 },
    inventory: { stock: 180, minStock: 35, maxStock: 500, unit: "pieces" },
    specifications: { weight: "24g", expiryDate: new Date(Date.now() + 730*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop&crop=center"],
    tags: ["cold", "flu", "fever", "relief"],
    features: ["Multi-symptom", "Fast acting", "Non-drowsy"],
    ratings: { average: 4.0, count: 155 },
    analytics: { views: 360, purchases: 92, trendingScore: 78 },
    supplier: { name: "Cold Care Pharma", contact: "+91 9876543236" },
    isFeatured: false,
    isNewLaunch: false,
    businessType: "pharmacy"
  },
  {
    name: "First Aid Kit",
    description: "Complete first aid kit with essential medical supplies",
    category: "Medical Supplies",
    subcategory: "First Aid",
    brand: "LifeGuard",
    sku: "LG-FIRSTAID-KIT",
    price: { mrp: 105, discountedPrice: 95, discount: 9.52 },
    inventory: { stock: 65, minStock: 15, maxStock: 200, unit: "pieces" },
    specifications: { weight: "500g", expiryDate: new Date(Date.now() + 1460*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400&h=400&fit=crop&crop=center"],
    tags: ["first aid", "emergency", "medical supplies", "safety"],
    features: ["Complete kit", "Portable case", "Essential supplies"],
    ratings: { average: 4.5, count: 98 },
    analytics: { views: 310, purchases: 72, trendingScore: 74 },
    supplier: { name: "Emergency Medical Co", contact: "+91 9876543237" },
    isFeatured: true,
    isNewLaunch: false,
    businessType: "pharmacy"
  },
  {
    name: "Calcium Tablets",
    description: "Calcium with Vitamin D3 for bone health - 30 tablets",
    category: "Medicine",
    subcategory: "Vitamins & Supplements",
    brand: "Shelcal",
    sku: "SHE-CALCIUM-30T",
    price: { mrp: 80, discountedPrice: 72, discount: 10 },
    inventory: { stock: 190, minStock: 40, maxStock: 550, unit: "pieces" },
    specifications: { weight: "60g", expiryDate: new Date(Date.now() + 730*24*60*60*1000) },
    images: ["https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop&crop=center"],
    tags: ["calcium", "vitamin D3", "bone health", "supplement"],
    features: ["With Vitamin D3", "Better absorption", "Bone strength"],
    ratings: { average: 4.4, count: 175 },
    analytics: { views: 290, purchases: 85, trendingScore: 76 },
    supplier: { name: "Bone Health Specialists", contact: "+91 9876543238" },
    isFeatured: false,
    isNewLaunch: false,
    businessType: "pharmacy"
  }
];

async function reseedProducts() {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/qwipo-recommendations');
    console.log('Connected to MongoDB');
    
    const Product = require('./src/models/Product');
    
    // Clear existing products first
    console.log('Clearing existing products...');
    await Product.deleteMany({});
    console.log('Existing products cleared');
    
    // Insert new products with correct images and business types
    const insertedProducts = await Product.insertMany(sampleProducts);
    console.log(`Inserted ${insertedProducts.length} products with correct images and business types`);
    
    // Display summary of inserted products by business type
    const businessTypeCounts = {};
    insertedProducts.forEach(product => {
      businessTypeCounts[product.businessType] = (businessTypeCounts[product.businessType] || 0) + 1;
    });
    
    console.log('\nProducts by business type:');
    Object.entries(businessTypeCounts).forEach(([type, count]) => {
      console.log(`  ${type}: ${count} products`);
    });
    
    console.log('Products reseeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error reseeding products:', error);
    process.exit(1);
  }
}

reseedProducts();